name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c
        with:
          go-version: 1.24.2
          cache: true

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.2.0
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run linting for ${{ matrix.goos }}
        env:
          GOOS: ${{ matrix.goos }}
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Verify vendor/ is not present
        run: stat vendor && exit 1 || exit 0

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c
        with:
          go-version: 1.24.2
          cache: true

      - name: Check go mod tidy
        run: |
          go mod tidy
          go mod tidy -C cmd/cli
          go work sync
          git diff --exit-code go.mod go.sum cmd/cli/go.mod cmd/cli/go.sum go.work go.work.sum

      - name: Run tests with race detection
        run: go test -race ./...

      - name: validate
        run: make validate

      - name: model-distribution # TODO: Create a single Makefile for the monorepo
        run: make -C ./pkg/distribution/ all
