name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          go-version: 1.25.6
          cache: true

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20
        with:
          version: v2.7.2
          install-only: true

      - name: Run linting for ${{ matrix.goos }}
        env:
          GOOS: ${{ matrix.goos }}
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Verify vendor/ is not present
        run: stat vendor && exit 1 || exit 0

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          go-version: 1.25.6
          cache: true

      - name: Check go mod tidy
        run: |
          go mod tidy
          go mod tidy -C cmd/cli
          go work sync
          git diff --exit-code go.mod go.sum cmd/cli/go.mod cmd/cli/go.sum go.work go.work.sum

      - name: Run tests with race detection
        run: go test -race ./...

      - name: validate
        run: make validate
